#! /bin/sh

set -e

CVERSION=`dpkg-query -W -f='${Version}' libpcan-kernel-source | sed 's/~.*$//'`

case "$1" in
  remove|upgrade)
    echo "Removing all DKMS Modules"
    dkms remove -m libpcan -v $CVERSION --all > /dev/null
    echo "Done."
    ;;
esac

exit 0
